name: semanticbits-kata-jpserquina
recipe: drupal9
config:
  webroot: .
  php: '7.4'
  composer_version: '1.10.1'
  via: nginx
  database: mysql
  xdebug: true
services:
  appserver:
    build:
      - composer install
